export default {
  providerErrorMsg: (context: string, provider: string) => `${context} must be used within an ${provider}`,
  schemaValidationError: {
    description: 'Description is required',
    category: 'Category is required',
    date: 'Date is required',
    amount: 'Amount is required',
    email: 'E-mail is required',
    emailFormat: 'Invalid e-mail format',
    password: 'Password is required',
    paymentType: 'Payment type is required',
    bank: 'Bank name is required',
    store: 'Store name is required',
    month: 'Month is required',
    balanceType: 'Balance type is required',
  },
  alreadyExistingExpense: 'This expense is already registered',
  alreadyExistingPaymentType: 'Payment type already exists',
  alreadyExistingCategory: 'Category already exists',
  alreadyExistingBank: 'Bank already exists',
  alreadyExistingStore: 'Store already exists',
  alreadyExitingUpdatePaymentType: 'There is already a payment type with same description',
  alreadyExitingUpdateCategory: 'There is already a category with same description',
  alreadyExitingUpdateBank: 'There is already a bank with same name',
  alreadyExitingUpdateStore: 'There is already a store with same name',
  toastErrors: {
    title: {
      authentication: 'Authentication error',
      creation: 'Create expense error',
    },
    description: {
      existingExpense: 'This expense is already registered for this day',
      creation: 'Error on creating expense',
      login: 'Error on login',
      bankRequired: 'You must select a bank for this payment type',
    },
  },
  businessErrors: { bankRequired: 'bankRequired' },
}
